version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: userregistration-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: user_registration
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./user-registration-be
      dockerfile: Dockerfile
    container_name: userregistration-backend
    restart: unless-stopped
    env_file:
      - ./user-registration-be/.env.template
    environment:
      # Override the MONGO_URI to point to the mongo service inside compose
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=user_registration
      - JWT_SECRET=my_jwt_secret
      - CORS_ORIGIN=http://localhost:5173
      - PORT=3000
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./user-registration-fe
      dockerfile: Dockerfile
    container_name: userregistration-frontend
    restart: unless-stopped
    ports:
      # Map host 5173 to the container's nginx port 80 so CORS_ORIGIN in backend works by default
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data:

networks:
  default:
    driver: bridge
